// Generated by @annetaan/leko-codegen. Do not edit.
//
// Every name here is reported by a reached() call in this project. To add a
// signal, write the call and run the generator again.

declare module '@annetaan/leko' {
  interface LekoSignals {
    /** src/cases/branching.ts:61 */
    'lines-checked': true
    /** src/cases/signal-too-early.ts:39 */
    /** src/cases/two-stories.ts:40 */
    'order-placed': true
    /** src/cases/branching.ts:70 */
    /** src/cases/signal-too-early.ts:44 */
    /** src/cases/signal-too-early.ts:51 */
    'order-sent': true
    /** src/cases/next-control.ts:36 */
    'project-renamed': true
  }

  // The vocabulary above came from the call sites, so a name missing from it
  // is a name nothing reports. This makes awaits reject one. reached() is
  // never tightened. Run the generator with --loose to drop this block.
  interface LekoStrict {
    strict: true
  }
}

/**
 * Unused, and load-bearing. A file with no import and no export is not a module,
 * and a `declare module` block inside one declares an ambient module rather than
 * augmenting anything. This export is what makes the block above real.
 */
export type GeneratedByLekoCodegen = true
