import type { ScanResult, Site } from './scan.js'

export interface EmitOptions {
  /**
   * Whether the file promises the vocabulary is complete, which is what makes
   * an unknown name in `awaits` fail to compile. Defaults to `true`.
   *
   * The promise is only worth making about a vocabulary that came from the call
   * sites. Pass `false` for a project that builds signal names at runtime, where
   * a scan cannot see all of them.
   */
  strict?: boolean
  /** Where the sites in the comments are written relative to. */
  root?: string
}

const relative = (site: Site, root: string | undefined): string => {
  const path = root && site.file.startsWith(root) ? site.file.slice(root.length + 1) : site.file
  return `${path}:${site.line}`
}

/** A string TypeScript will read back as the same key. */
const key = (name: string): string => `'${name.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

/**
 * The declaration file for a scan.
 *
 * Every line of it is derived from the argument, so the same project emits the
 * same bytes and `--check` can compare them.
 *
 * It ends in an export on purpose. A `declare module` block augments a module
 * only from inside another module, and a file holding nothing but that block is
 * not one. Without the export this file would quietly declare an ambient module
 * called `@annetaan/leko`, no completion would appear, and nothing would report
 * a problem.
 *
 * A named type rather than `export {}`, which several linters read as an empty
 * specifier and offer to delete. Deleting it breaks the file in a way nothing
 * reports, so it is not worth leaving somebody that offer.
 */
export function emit(result: ScanResult, options: EmitOptions = {}): string {
  const strict = options.strict ?? true
  const lines: string[] = [
    '// Generated by @annetaan/leko-codegen. Do not edit.',
    '//',
    '// Every name here is reported by a reached() call in this project. To add a',
    '// signal, write the call and run the generator again.',
    '',
    "declare module '@annetaan/leko' {",
    '  interface LekoSignals {',
  ]

  if (result.signals.length === 0) {
    lines.push('    // No reached() call in this project reports a name a scan could read.')
  }

  for (const signal of result.signals) {
    for (const site of signal.sites) lines.push(`    /** ${relative(site, options.root)} */`)
    lines.push(`    ${key(signal.name)}: true`)
  }

  lines.push('  }')

  if (strict) {
    lines.push(
      '',
      '  // The vocabulary above came from the call sites, so a name missing from it',
      '  // is a name nothing reports. This makes awaits reject one. reached() is',
      '  // never tightened. Run the generator with --loose to drop this block.',
      '  interface LekoStrict {',
      '    strict: true',
      '  }',
    )
  }

  lines.push(
    '}',
    '',
    '/**',
    ' * Unused, and load-bearing. A file with no import and no export is not a module,',
    ' * and a `declare module` block inside one declares an ambient module rather than',
    ' * augmenting anything. This export is what makes the block above real.',
    ' */',
    'export type GeneratedByLekoCodegen = true',
    '',
  )

  return lines.join('\n')
}
